name = "ebay-accounting"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
database_id = "63d64687-5cfb-43fd-9549-41f2c17c7988"
binding = "DB"
database_name = "DB"

[[r2_buckets]]
bucket_name = "ebay-accounting"
binding = "BUCKET"

